## Author: nspark
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: WoodongKing Serverless Project
Globals:
    Function:
        Environment:
            Variables:
Resources:
    UserSignUp:
        Type: AWS::Serverless::Function
        Properties:
            Handler: main
            Runtime: go1.x
            CodeUri: ./router/userSignUp
            Description: user sign up
            MemorySize: 1024
            Timeout: 240
            Events:
                HttpPost:
                    Type: Api
                    Properties:
                        Path: /user/signup
                        Method: post
